### PR TITLE
Fix a handful of annoying things

### LINKED ISSUE #495: nimbleDir ignored with custom tasks
A custom `--nimbleDir` seems to be ignored when executing a user-defined task.

**Running a pre-defined task:** no packages.json in the newly created nimble directory. This is expected behaviour.
```
 % nimble --nimbleDir:tmp1 --verbose build        
    Setting Nim stdlib prefix to 
    Setting Nim stdlib path to /home/kea/.choosenim/toolchains/nim-0.18.0/lib
  Verifying dependencies for dummy_nim@0.1.0
    Reading official package list
    Prompt: No local packages.json found, download it from internet? [y/N]
```

**Running a custom task:** a packages.json is somehow found despite the custom nimble directory being empty. The dependencies are installed in the wrong directory.
```
 % nimble --nimbleDir:tmp2 --verbose build_example 
    Setting Nim stdlib prefix to 
    Setting Nim stdlib path to /home/kea/.choosenim/toolchains/nim-0.18.0/lib
  Executing task build_example in /home/kea/code/dummy-nim/dummy_nim.nimble
    Setting Nim stdlib prefix to 
    Setting Nim stdlib path to /home/kea/.choosenim/toolchains/nim-0.18.0/lib
  Verifying dependencies for dummy_nim@0.1.0
    Reading official package list
   Checking for jester@any version
 Installing jester@any version
    Reading official package list
Downloading https://github.com/dom96/jester using git
    Cloning latest tagged version: v0.2.0
    Setting Nim stdlib prefix to 
    Setting Nim stdlib path to /home/kea/.choosenim/toolchains/nim-0.18.0/lib
  Verifying dependencies for jester@0.2.0
 Installing jester@0.2.0
    Copying file /tmp/nimble_27574/githubcom_dom96jester/changelog.markdown to /home/kea/.nimble/pkgs/jester-0.2.0/changelog.markdown
    Copying file /tmp/nimble_27574/githubcom_dom96jester/license.txt to /home/kea/.nimble/pkgs/jester-0.2.0/license.txt
    Copying file /tmp/nimble_27574/githubcom_dom96jester/jester.nimble to /home/kea/.nimble/pkgs/jester-0.2.0/jester.nimble
    Copying file /tmp/nimble_27574/githubcom_dom96jester/readme.markdown to /home/kea/.nimble/pkgs/jester-0.2.0/readme.markdown
    Copying file /tmp/nimble_27574/githubcom_dom96jester/jester.nim to /home/kea/.nimble/pkgs/jester-0.2.0/jester.nim
    Copying file /tmp/nimble_27574/githubcom_dom96jester/jester/private/utils.nim to /home/kea/.nimble/pkgs/jester-0.2.0/jester/private/utils.nim
    Copying file /tmp/nimble_27574/githubcom_dom96jester/jester/private/patterns.nim to /home/kea/.nimble/pkgs/jester-0.2.0/jester/private/patterns.nim
    Copying file /tmp/nimble_27574/githubcom_dom96jester/jester/private/errorpages.nim to /home/kea/.nimble/pkgs/jester-0.2.0/jester/private/errorpages.nim
    Copying file /tmp/nimble_27574/githubcom_dom96jester/jester.nimble to /home/kea/.nimble/pkgs/jester-0.2.0/jester.nimble
   Success: jester installed successfully.
```

**dummy_nim.nimble:**
```
version       = "0.1.0"
author        = "kea"
description   = "A dummy package"
license       = "MIT"
srcDir        = "src"
bin           = @["dummy_nim"]

requires "nim >= 0.18.0"
requires "jester"

task build_example, "Build example":
  setCommand "c", "example/example.nim"
```

### LINKED ISSUE #533: Running `nimble build` on a project does not run `before install` on dependencies
Consider: nimbletest.nimble
```
version = "0.1.0"
author = "anonymous"
description = "something"
license = "MIT"

bin = @["nimbletest"]

requires "https://github.com/genotrance/nimtess2.git"
```

nimbletest.nim
```
import nimtess2/tesselator
```

When you run `nimble build` on this project, it attempts to install nimtess2 but doesn't run the `before install` step where nimgen is installed and run on the wrapper. As a result, this package does not build.

```
> nimble build

  Verifying dependencies for a@0.1.0
 Installing https://github.com/genotrance/nimtess2.git@>= 0.1.0
Downloading https://github.com/genotrance/nimtess2.git using git
  Verifying dependencies for nimtess2@0.1.0
      Info: Dependency on nimgen@>= 0.4.0 already satisfied
  Verifying dependencies for nimgen@0.4.0
      Info: Dependency on c2nim@>= 0.9.13 already satisfied
   Warning: Package 'c2nim' has an incorrect structure. The top level of the package source directory should contain at most one module, named 'c2nim.nim', but a file named 'cpp.nim' was found. This will be an error in the future.
      Hint: If this is the primary source file in the package, rename it to 'c2nim.nim'. If it's a source file required by the main module, or if it is one of several modules exposed by 'c2nim', then move it into a 'c2nimpkg/' subdirectory. If it's a test file or otherwise not required to build the the package 'c2nim.nim', prevent its installation by adding `skipFiles = @["cpp.nim"]` to the .nimble file. See https://github.com/nim-lang/nimble#libraries for more info.
  Verifying dependencies for c2nim@#head
      Info: Dependency on compiler@>= 0.16.0 already satisfied
  Verifying dependencies for compiler@#head
      Info: Dependency on regex@>= 0.7.1 already satisfied
  Verifying dependencies for regex@0.7.3
      Info: Dependency on unicodedb@>= 0.5.1 & < 0.6 already satisfied
  Verifying dependencies for unicodedb@0.5.1
      Info: Dependency on unicodeplus@>= 0.3.0 & < 0.4 already satisfied
  Verifying dependencies for unicodeplus@0.3.2
      Info: Dependency on unicodedb@>= 0.4 & < 0.6 already satisfied
  Verifying dependencies for unicodedb@0.5.1
 Installing nimtess2@0.1.0
   Success: nimtess2 installed successfully.
   Building a/a using c backend
       Tip: 40 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: a
        ... Details:
        ... Execution failed with exit code 1
        ... Command: "/home/genotrance/.nimble/bin/nim" c --noBabelPath --path:"/home/genotrance/.nimble/pkgs/nimgen-0.4.0"  --path:"/home/genotrance/.nimble/pkgs/c2nim-#head"  --path:"/home/genotrance/.nimble/pkgs/compiler-#head"  --path:"/home/genotrance/.nimble/pkgs/regex-0.7.3"  --path:"/home/genotrance/.nimble/pkgs/unicodedb-0.5.1"  --path:"/home/genotrance/.nimble/pkgs/unicodeplus-0.3.2"  --path:"/home/genotrance/.nimble/pkgs/unicodedb-0.5.1"  --path:"/tmp/nimble_19103/githubcom_genotrancenimtess2git_0.1.0"  -o:"/home/genotrance/a/a" "/home/genotrance/a/a.nim"
        ... Output: Hint: used config file '/home/genotrance/programming/nimdevel/config/nim.cfg' [Conf]
        ... Hint: system [Processing]
        ... Hint: a [Processing]
        ... a.nim(1, 16) Error: cannot open file: nimtess2/tesselator
```

Note that if you do `nimble install` instead of `nimble build`, it works just fine.

```
> nimble install

  Verifying dependencies for a@0.1.0
 Installing https://github.com/genotrance/nimtess2.git@>= 0.1.0
Downloading https://github.com/genotrance/nimtess2.git using git
Downloading https://github.com/genotrance/nimgen using git
  Verifying dependencies for nimgen@0.4.0
      Info: Dependency on c2nim@>= 0.9.13 already satisfied
  Verifying dependencies for c2nim@#head
      Info: Dependency on compiler@>= 0.16.0 already satisfied
  Verifying dependencies for compiler@#head
      Info: Dependency on regex@>= 0.7.1 already satisfied
  Verifying dependencies for regex@0.7.3
      Info: Dependency on unicodedb@>= 0.5.1 & < 0.6 already satisfied
  Verifying dependencies for unicodedb@0.5.1
      Info: Dependency on unicodeplus@>= 0.3.0 & < 0.4 already satisfied
  Verifying dependencies for unicodeplus@0.3.2
      Info: Dependency on unicodedb@>= 0.4 & < 0.6 already satisfied
  Verifying dependencies for unicodedb@0.5.1
 Installing nimgen@0.4.0
   Building nimgen/nimgen using c backend
    Prompt: nimgen@0.4.0 already exists. Overwrite? -> [forced yes]
   Success: nimgen installed successfully.
Setting up Git repo               <====== nimgen actually being run in before install
Checking out artifacts
Processing nimtess2/Include/tesselator.h
Generating nimtess2/tesselator.nim
Processing nimtess2/tesselator.nim
  Verifying dependencies for nimtess2@0.1.0
      Info: Dependency on nimgen@>= 0.4.0 already satisfied
  Verifying dependencies for nimgen@0.4.0
      Info: Dependency on c2nim@>= 0.9.13 already satisfied
  Verifying dependencies for c2nim@#head
      Info: Dependency on compiler@>= 0.16.0 already satisfied
  Verifying dependencies for compiler@#head
      Info: Dependency on regex@>= 0.7.1 already satisfied
  Verifying dependencies for regex@0.7.3
      Info: Dependency on unicodedb@>= 0.5.1 & < 0.6 already satisfied
  Verifying dependencies for unicodedb@0.5.1
      Info: Dependency on unicodeplus@>= 0.3.0 & < 0.4 already satisfied
  Verifying dependencies for unicodeplus@0.3.2
      Info: Dependency on unicodedb@>= 0.4 & < 0.6 already satisfied
  Verifying dependencies for unicodedb@0.5.1
 Installing nimtess2@0.1.0
   Success: nimtess2 installed successfully.
 Installing a@0.1.0
   Building a/a using c backend
   Success: a installed successfully.
```

### LINKED ISSUE #563: crash in parsing the version [regression]
This is my config for a long time now. I didn't change anything recently.

```nim
version       = "0.3.1"
author        = "Arne Döring"
description   = "nice way of handling render code"
license       = "MIT"

bin           = @[
  "examples/deferred_shading",
  "examples/forward_vertex_shader",
  "examples/hello_shapes",
  "examples/hello_triangle",
  "examples/mandelbrot",
  "examples/iqm_mesh_loading",
  "examples/neuralnetwork",
  "examples/noise_landscape",
  "examples/particles",
  "examples/particles_transform_feedback",
  "examples/player_controls",
  "examples/retro_tiling",
  "examples/sandbox",
  "examples/tetris",
  "examples/waves",
  "examples/console",
]

skipDirs = @["unittests", "experiment"]

#[ Dependencies ]#

requires @[
  "nim                  >= 0.18.1  ",
  "AntTweakBar          >= 1.0.2   ",
  "sdl2_nim             >= 2.0.6.1 ",
  "glm                  >= 1.1.1   ",
  "ast_pattern_matching >= 1.0.0   ",
  #"fftw3               >= 0.1.0   ", # add this if you want audiotest to work
]

task run, "run all examples":
  for binary in bin:
    exec(binary)
```

This is the strack trace of ``nimble build``

```
nimble.nim(1105)         nimble
nimble.nim(1063)         doAction
nimble.nim(505)          build
packageparser.nim(410)   getPkgInfo
packageparser.nim(398)   getPkgInfoFromFile
packageparser.nim(349)   readPackageInfo
nimscriptsupport.nim(589) readPackageInfoFromNims
nimscriptsupport.nim(86) extractRequires
version.nim(218)         parseRequires
version.nim(193)         parseVersionRange
system.nim(2939)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
```

### LINKED ISSUE #606: before/after hooks for 'build' are not run
The following in a '.nimble' file:
```
before build:
   echo "before build"
after build:
   echo "after build"
```
should print:
```
before build
...
after build
```
when called with `nimble build` but they are never run.

### PR DESCRIPTION
**Pull request by LemonBoy**
I cannot figure how to run the test harness so fuck it

Fixes #495 
Fixes #563
Fixes #533 
Fixes #606

### CODE REVIEW

File: src/nimble.nim [hunk 1]
```diff
@@ -214,13 +214,20 @@ proc processDeps(pkginfo: PackageInfo, options: Options): seq[PackageInfo] =
     addRevDep(options.nimbleData, i, pkginfo)
 
 proc buildFromDir(pkgInfo: PackageInfo, paths: seq[string],
-                  args: var seq[string]) =
+                  args: var seq[string], options: Options) =
+  doAssert(options.action.typ == actionBuild)
```
Comment (dom96) [inline src/nimble.nim]: I'm surprised this doesn't break when calling ``nimble install``. Either the test coverage is bad or I'm missing something. But why did you add these asserts?

File: src/nimble.nim [hunk 2]
```diff
@@ -356,7 +368,9 @@ proc installFromDir(dir: string, requestedVer: VersionRange, options: Options,
   # if the build fails then the old package will still be installed.
   if pkgInfo.bin.len > 0:
     let paths = result.deps.map(dep => dep.getRealDir())
-    buildFromDir(pkgInfo, paths, true)
+    var optsCopy = options.briefClone()
+    optsCopy.action.typ = actionBuild
```
Comment (dom96) [inline src/nimble.nim]: oh... but why do it this way?

File: src/nimble.nim (hunk 1 above)
Comment (LemonBoy) [reply src/nimble.nim]: Sanity check. I've checked all the entry points and the assert doesn't fire.

File: src/nimble.nim (hunk 2 above)
Comment (LemonBoy) [reply src/nimble.nim]: That's the least invasive way to stack `options`. Doing it this way keeps the invariant where we enter the procedures doing the action with the correct `typ` set.

Comment (dom96) [reply src/nimble.nim]: What do you mean by "stack ``options``", why do you need to do this? 

This looks like a bit of a workaround to me, and you'll undoubtedly get cases where some flags in options are lost because they have not been carried over in ``briefClone``. I just don't understand why this is necessary, why make ``buildFromDir`` expect to only be called for an options with an ``actionBuild``? It doesn't reflect the options that were passed to the application.

Comment (LemonBoy) [reply src/nimble.nim]: > This looks like a bit of a workaround to me

It works around a broken design, yes.

> you'll undoubtedly get cases where some flags in options are lost because they have not been carried over in briefClone

I did not introduce this pattern, I've only re-used it for more cases. #495 shows that it was not such a great idea to boot.

>  just don't understand why this is necessary, why make buildFromDir expect to only be called for an options with an actionBuild

You didn't read #533, didn't you? Right now calling `nimble build` propagates the `build` option to every sub-task and that's incredibly wrong if nimble is actually **building** and **installing** some dependencies. The user specified action tells you what to do but should not have any impact on the sub-tasks coordinated by nimble. Another example is the `nimble install` process: the difference between `nimble build` and `nimble install` is that the latter copies some artifacts over to some directory. You can also describe it as `build` + `copy` and it makes sense to propagate `actionBuild` during the first phase and `actionInstall` during the latter because you don't want to duplicate your `task` logic between `build` and `install`.

Comment (dom96) [reply src/nimble.nim]: > I did not introduce this pattern, I've only re-used it for more cases. #495 shows that it was not such a great idea to boot.

From what I can tell #495 has nothing to do with how options are handled. It exists simply because the options are not propagated to Nimscript's ``exec``. In fact, it's debatable whether they should be, or whether we should offer an API to retrieve the options and make it easy to pass onto commands.

> Right now calling `nimble build` propagates the `build` option to every sub-task and that's incredibly wrong if nimble is actually **building** and **installing** some dependencies

The ``options`` reflect what Nimble was executed with. Perhaps this is a bad design, but it was created before "tasks" were even conceived.

> Another example is the `nimble install` process: the difference between `nimble build` and `nimble install` is that the latter copies some artifacts over to some directory. You can also describe it as `build` + `copy` and it makes sense to propagate `actionBuild` during the first phase and `actionInstall` during the latter because you don't want to duplicate your `task` logic between `build` and `install`.

Yes, I understand that. But I don't understand what actually changing the options gets you, you're calling the hook for ``actionBuild`` in ``buildFromDir``, I don't see any checks for what kind of options we got. Did you literally just add it as a sanity check?

**Comment by dom96** [comment]
This wasn't ready to be merged yet. Why did you merge this?
