### PR TITLE
Be less ambiguous when a project isn't under a VCS like Git or Mercurial

### LINKED ISSUE #1180: Nimble commands fail after `git init`
I've tried to run `nimble lock` on a directory which wasn't under version control, and I got this message:

```
    Error:  Sync file require current working directory to be under some supported type of version control.
     Hint:  Put package's working directory under version control.
```

(and this still created `nimble.lock` file, btw)

----

After that, I've run `git init`, and now `nimble lock` produces:

```
$ nimble lock
       Tip: 2 messages have been suppressed, use --verbose to show them.
tools.nim(62)            tryDoCmdEx

    Error:  Execution of 'git -C /home/miran/code/nim-lang/tests/myPackage rev-parse HEAD' failed with an exit code 128.
        ... Details: fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
        ... Use '--' to separate paths from revisions, like this:
        ... 'git <command> [<revision>...] -- [<file>...]'
        ... HEAD
```

The same error appears on _some_ other commands (e.g. `nimble check`, `nimble test`, or non-existing commands such as `nimble foobar`), but not on others (e.g. `nimble tasks` or `nimble list -i`).

-----

The issue is resolved after one makes a first commit. But then the original hint ("Put package's working directory under version control.") should be changed to reflect that just initializing git isn't enough.

### PR DESCRIPTION
**Pull request by xTrayambak**
This PR fixes #1180 by:
1) Fixing the first hint to tell the user to put the package's working directory under version control AND make a commit.
2) If they still choose to ignore it and just put the package's working directory under version control without making a commit, the subsequent errors will hint at the user to make a commit.

### CODE REVIEW

File: src/nimblepkg/packageparser.nim [hunk 1]
```diff
@@ -347,14 +347,14 @@ proc readPackageInfo(pkgInfo: var PackageInfo, nf: NimbleFile, options: Options,
   ## This version uses a cache stored in ``options``, so calling it multiple
   ## times on the same ``nf`` shouldn't require re-evaluation of the Nimble
   ## file.
-
+
```
Comment (Araq) [inline src/nimblepkg/packageparser.nim:350]:
```suggestion

```

File: src/nimblepkg/packageparser.nim [hunk 2]
```diff
@@ -347,14 +347,14 @@ proc readPackageInfo(pkgInfo: var PackageInfo, nf: NimbleFile, options: Options,
...
-
+  
   assert fileExists(nf)
 
   # Check the cache.
   if options.pkgInfoCache.hasKey(nf):
     pkgInfo = options.pkgInfoCache[nf]
     return
-
+
```
Comment (Araq) [inline src/nimblepkg/packageparser.nim:357]:
```suggestion

```
