### PR TITLE
show cmd used with --verbose (even on success); fix #783

### LINKED ISSUE #783: [CI] travis always fails for nim=#hash after the 1st run
not sure about "always" but that's my best guess: 
see https://github.com/nim-lang/nimble/pull/782 which really should be a noop.
It fails for `BRANCH=#ab525cc48abdbbbed1f772e58e9fe21474f70f07` (see .travis.yml)

image

logs:
https://gist.github.com/timotheecour/1dafdee664d5f26f1551d91b473c3b94

shows (on linux, similar on other OS):

```
$ nim c -r tester
The program 'nim' is currently not installed. To run 'nim' please ask your administrator to install the package 'nim'
The command "nim c -r tester" exited with 127.
```

## note
it seems to only fail after the 1st push, perhaps because of caching: for the 1st push it doesn't use cache and works, after the 1st push it uses cache and fails

### PR DESCRIPTION
**Pull request by timotheecour**
before PR:
`nimble install -y -p:-u:release https://github.com/genotrance/nimgen`
doesn't show the actual command used and instead shows the un-informative:
`Building nimgen/nimgen.exe using c backend`
even with --verbose

after PR:
shows the actual cmd used with --verbose, eg:

```
cmd /Users/timothee/.nimble/bin/nim c --noNimblePath -d:NimblePkgVersion=0.5.1 -u:release -d:release --path:"/Users/timothee/.nimble/pkgs/c2nim-0.9.14"  --path:"/Users/timothee/git_clone/nim/nim-regex/src"  --path:"/Users/timothee/git_clone/nim/nim-unicodedb/src"  --path:"/Users/timothee/.nimble/pkgs/unicodeplus-0.5.1"  --path:"/Users/timothee/git_clone/nim/nim-unicodedb/src"  -o:"/var/folders/ll/dtd6ksrn50n3xkdy4y61tf_80000gn/T/nimble_16626/githubcom_genotrancenimgen/nimgen" /var/folders/ll/dtd6ksrn50n3xkdy4y61tf_80000gn/T/nimble_16626/githubcom_genotrancenimgen/src/nimgen.nim
```

which (besides being generally useful) actually shows why -u:release wasn't effective prior to this PR, since `-d:release` was passed after; I'm also fixing that in this PR so that -p:-u:release is honored

* fix https://github.com/nim-lang/nimble/issues/783

### CODE REVIEW

File: src/nimble.nim [hunk 1]
```diff
@@ -251,10 +251,13 @@ proc buildFromDir(
...
+    let input = realDir / bin.changeFileExt("nim")
+    let cmd = "$# $# --noNimblePath $# $# $# $#" %
+            [getNimBin().quoteShell, pkgInfo.backend, nimblePkgVersion,
+             join(args, " "), outputOpt, input.quoteShell]
+    display("cmd", cmd, priority = MediumPriority)
     try:
-      doCmd("\"" & getNimBin() & "\" $# --noNimblePath $# $# $# \"$#\"" %
-            [pkgInfo.backend, nimblePkgVersion, join(args, " "), outputOpt,
-             realDir / bin.changeFileExt("nim")])
+      doCmd(cmd)
```
Comment (dom96) [inline src/nimble.nim]: Instead of doing this, please pass a new flag to `doCmd` and change https://github.com/nim-lang/nimble/blob/master/src/nimblepkg/tools.nim#L23.

Comment (timotheecour) [reply src/nimble.nim]: done

**Comment by timotheecour** [comment]
PTAL

File: src/nimble.nim [hunk 2]
```diff
@@ -251,10 +251,14 @@ proc buildFromDir(
...
+    # `quoteShell` would be more robust than `\"` (and avoid quoting when
+    # un-necessary) but would require changing `extractBin`
+    let cmd = "\"$#\" $# --noNimblePath $# $# $# \"$#\"" %
+            [getNimBin(), pkgInfo.backend, nimblePkgVersion,
+             join(args, " "), outputOpt, input]
     try:
-      doCmd("\"" & getNimBin() & "\" $# --noNimblePath $# $# $# \"$#\"" %
-            [pkgInfo.backend, nimblePkgVersion, join(args, " "), outputOpt,
-             realDir / bin.changeFileExt("nim")])
+      doCmd(cmd, showCmd = true)
```
Comment (dom96) [inline src/nimble.nim]: This doesn't check for ``verbose`` unless I'm missing something.

Comment (timotheecour) [reply src/nimble.nim]: without --verbose, `display("Executing", cmd, priority = MediumPriority)` won't print anything because of `MediumPriority`
with --verbose, `display("Executing", cmd, priority = MediumPriority)` will print

as you can verify with (after rebuilding nimble after this PR):
```
nim c -o:nimble2 src/nimble.nim
./nimble2 install -y https://github.com/genotrance/nimgen
./nimble2 install -y -p:-u:release --verbose https://github.com/genotrance/nimgen
```

(or `./nimble2 install -y -p:-u:release --verbose https://github.com/genotrance/nimgen` to verify the other change I did)

**Comment by timotheecour** [comment]
PTAL
> Tests need to be fixed as well, are they flaky?

that's because of https://github.com/nim-lang/nimble/issues/783
